#!/usr/bin/python
# -*- coding: UTF-8 -*-
import argparse
import niprov

parser = argparse.ArgumentParser(
    description='Enter provenance of a new file created as the result of a transformation of an existing file.')
parser.add_argument('transformation', help='Name of the transformation applied.')
parser.add_argument('ancestor', help='Image that was the basis of the transformation.')
parser.add_argument('new', help='Where the resulting image was stored.')

args = parser.parse_args()
niprov.record(args.transformation, args.ancestor, args.new)
